services:
  runtime:
    pull_policy: build
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_URL=${MONGO_URL}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build: .
